baseURL = "https://judica.org/"
languageCode = "en-us"
title = "Judica, Inc"
theme = "judica"
copyright = "&copy; Judica, Inc 2020 | contact@judica.org | <a class='darkmode-switch'> dark/light theme</a>"

[[menu.main]]
    identifier = "about"
    name = "about."
    url = "/about/"
    weight = -160
[[menu.main]]
    identifier = "software"
    name = "software."
    url = "/software/"
    weight = -140
[[menu.main]]
    identifier = "blog"
    name = "blog."
    url = "/blog/"
    weight = -120
[[menu.main]]
    identifier = "join"
    name = "join."
    url = "/join/"
    weight = -110
[params]
    missions = ["self-custody for all.", "vibrant bitcoin economy.", "unbreakable base layer."]
    slogan = "restore the  balance"
    brand="judica."
    headerimage="img/wizard2.gif"
